spring.application.name=reservas

spring.datasource.url=jdbc:postgresql://localhost:5432/reservas
spring.datasource.username=usuario_reservas
spring.datasource.password=senha
spring.jpa.hibernate.ddl-auto=validate
